name: firecrawl
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: forgettherules/firecrawl
  http_port: 3002
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: firecrawl
  source_dir: apps/api
  envs:
    - key: API_KEY
      scope: RUN_AND_BUILD_TIME
      value: "test_sk_123456789"
    - key: NUM_WORKERS_PER_QUEUE
      scope: RUN_AND_BUILD_TIME
      value: "8"
    - key: PORT
      scope: RUN_AND_BUILD_TIME
      value: "3002"
    - key: HOST
      scope: RUN_AND_BUILD_TIME
      value: "0.0.0.0"
    - key: REDIS_URL
      scope: RUN_AND_BUILD_TIME
      value: ${firecrawl2.DATABASE_URL}
    - key: REDIS_RATE_LIMIT_URL
      scope: RUN_AND_BUILD_TIME
      value: ${firecrawl2.DATABASE_URL}
    - key: USE_DB_AUTHENTICATION
      scope: RUN_AND_BUILD_TIME
      value: "true"
    - key: SUPABASE_URL
      scope: RUN_AND_BUILD_TIME
      value: "https://exmjcewmjunhqssbvwqy.supabase.co"
    - key: SUPABASE_ANON_TOKEN
      scope: RUN_AND_BUILD_TIME
      type: SECRET
      value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bWpjZXdtanVuaHFzc2J2d3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1MjAzODYsImV4cCI6MjA0NzA5NjM4Nn0.7pyclLORatW01C262jqwYpr2j5BS1JFWUAtyH-HGB7w"
    - key: SUPABASE_SERVICE_TOKEN
      scope: RUN_AND_BUILD_TIME
      type: SECRET
      value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bWpjZXdtanVuaHFzc2J2d3F5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMTUyMDM4NiwiZXhwIjoyMDQ3MDk2Mzg2fQ.gmroQPXKiwLAbZjvqsCmIQTsADXfvWBBHtuCMkTnBB4"
  run_command: /bin/sh -c "cd /app && pnpm run start:production" 